version: '3.8'

services:
  ffc-ahwr-dashboard:
    command: npm run start:watch
    build:
      target: development
    image: ffc-ahwr-dashboard-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/
